// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsoi3VNgPKjcbY22m3YappMI47YLe9IDs',
    appId: '1:282089342858:web:ec0a8c96ca75ef2a726a73',
    messagingSenderId: '282089342858',
    projectId: 'wellwisher-01',
    authDomain: 'wellwisher-01.firebaseapp.com',
    databaseURL: 'https://wellwisher-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wellwisher-01.appspot.com',
    measurementId: 'G-L9SFE15ML5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnO41CTQJxHJbmuwtCtnJX5W4GaeEwPAk',
    appId: '1:282089342858:android:f3bff2bb57d46898726a73',
    messagingSenderId: '282089342858',
    projectId: 'wellwisher-01',
    databaseURL: 'https://wellwisher-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wellwisher-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPs3JPK1t75wx7aAvfX7bEkwmcKF6WXM',
    appId: '1:282089342858:ios:ccb94ecc4e9e469e726a73',
    messagingSenderId: '282089342858',
    projectId: 'wellwisher-01',
    databaseURL: 'https://wellwisher-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wellwisher-01.appspot.com',
    iosBundleId: 'com.example.version1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPs3JPK1t75wx7aAvfX7bEkwmcKF6WXM',
    appId: '1:282089342858:ios:4de651b2bc19f77b726a73',
    messagingSenderId: '282089342858',
    projectId: 'wellwisher-01',
    databaseURL: 'https://wellwisher-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wellwisher-01.appspot.com',
    iosBundleId: 'com.example.version1.RunnerTests',
  );
}
